kind: pipeline
name: first

steps:
- name: yee
  image: alpine
  commands:
  - echo "run one"
  - env
  - echo "$${PLUGIN_TEST}"
  settings:
    test: "123123"
trigger:
  event:
  - "push"
---
kind: pipeline
name: test-tag
steps:
- name: wow
  image: alpine
  commands:
  - echo "AAAAAA"
  - echo "${DRONE_TAG}"
trigger:
  event:
  - "tag"
