kind: pipeline
name: first

steps:
- name: yee
  image: alpine
  commands:
  - echo "run one"
  when:
    event:
      include:
      - push
      - promote
    target:
      include:
      - t1
---
kind: pipeline
name: second

steps:
- name: wwww
  image: alpine
  commands:
  - echo "run two"
  when:
    target:
    - a
